### ISSUE TITLE
FileUtils.cp_r uses unsupported options on macOS causing issues with symbolic links

### ISSUE THREAD

**Issue by tekknovator** [ruby/fileutils#101]
The illegal options are -r instead of -R and --remove-destination instead of -f

Details:
While -r does not seem to be an issue on RHEL 9 it is on macOS 11.
Here is an excerpt from the macOS cp man page:

_COMPATIBILITY
     Historic versions of the cp utility had a -r option.  This implementation
     supports that option; however, its use is strongly discouraged, as it
     does not correctly copy special files, symbolic links, or fifo's._
 
--remove-destination functionality should be achieved via -f as the mode will change using -R  if the existing file has a different mode then the source

**Comment by nobu** [comment]
Do you mean the message when `verbose: true`?

**Comment by tekknovator** [comment]
Sorry for beeing unclear. It makes FileUtils.cp_r(preserve:true) ineffective on macOS.
In other words, macOS cp_r needs to wrap a different commandline then linux cp_r.
On linux, cp -r is ok.
On macOS, this does not work because Apples cp is different as stated in the man page excerpt shown in my previous comment.

It boils down to: cp is no longer cross platform compatible across unix shells. Sad :(

Hope this is better explained, sorry again for the confusion 😅

**Comment by nevinera** [comment]
I think there might be a misunderstanding - FileUtils is not invoking unix `cp` from its implementation of `cp_r` and `cp_lr`. It's a little confusing because there is a verbose-mode _message_ (that is constructed [here](https://github.com/ruby/fileutils/blob/master/lib/fileutils.rb#L987)) which is expressed in terms of `cp` flags, but the actual work is being invoked [here](https://github.com/ruby/fileutils/blob/master/lib/fileutils.rb#L990), which calls [this method](https://github.com/ruby/fileutils/blob/master/lib/fileutils.rb#L990), which handles `remove_destination` via the `File.unlink` call [here](https://github.com/ruby/fileutils/blob/master/lib/fileutils.rb#L1047).

If I'm misunderstanding, could you give an example situation in which the method produces unexpected behavior?

**Comment by tekknovator** [comment]
Thanks for pointing this out. I misunderstood the output for the actual call. However, the behaviour is similar as described in my initial report.

> If I'm the one with the misunderstanding, could you give an example situation in which the method produces unexpected behavior?

The unexpected behaviour happens when you try to copy symbolic links on macOS using the preserve option. The link will no longer link to the destination, but to itself.

**Comment by tekknovator** [comment]
Here is a script with a reproduction (sorry for only creating it now, should have made the effort in the first place). 
The output looks ok in terminal, but if open the finder info on the link after copying, you see it points to itself:

``` sh
#!/bin/zsh
#
# cleanup
# rm -Rf a_*
#
# Reproduction:
# create a file
touch a_touched_file

# create 2 folders
mkdir a_fodler_with_link a_folder_to_copy_to

# create a symbolic link in a folder, to a_touched_file
ln -s a_touched_file a_fodler_with_link/a_linked_file

# run command in ruby
ruby -e 'require "fileutils"; FileUtils.cp_r("a_fodler_with_link", "a_folder_to_copy_to/", remove_destination:true, preserve:true, verbose:false)'

echo 'showing repro result, please compare with finder'
ls -Rl a_folder_to_copy_to

```

**Comment by tekknovator** [comment]
@nobu yes, the message, as clarified by @nevinera but also the behaviour, as shown in the example above. Thanks for looking into this.

**Comment by tekknovator** [comment]
OK, this is embarassing. The link was never good in the first place because the path was relative.

**Comment by tekknovator** [comment]
see previous comment.
