### ISSUE TITLE
`FileUtils.rm_rf` doesn't raise when directory could not be removed

### ISSUE THREAD

**Issue by deivid-rodriguez** [ruby/fileutils#57]
I was investigating the cause of some permission issues in `bundler`, where files were failing to be created due to missing executable permissions in the parent folder.

I was really confused by this because `bundler` was supposed to freshly create the parent folder by calling `FileUtils.rm_rf` first on it, and then `FileUtils.mkdir_p` with proper permissions.

It turns out that if the folder exists, has some file inside, and has no executable permissions, `FileUtils.rm_rf` will fail to remove the target folder, but it will do it silently without giving any indication that something went wrong.

Compare shell behaviour:

```shell
$ mkdir foo; touch foo/bar; chmod -x foo; rm -rf foo; echo $?
rm: cannot remove 'foo/bar': Permission denied
1
```

with `FileUtils`

```shell
$ ruby -rfileutils -e 'Dir.mkdir "foo"; FileUtils.touch "foo/bar"; FileUtils.chmod "-x", "foo"; FileUtils.rm_rf "foo"'; echo $?
0
```

None of them actually manages to remove the "foo" folder, but the shell prints a proper error and exits with a proper status when this happens.

**Comment by deivid-rodriguez** [comment]
This was discussed at the dev meeting and the main conclusion was that this is not a bug, but a feature.

Since I reported this as bug, and it has been rejected as such, I'll close this!

Thanks!

**Comment by codiophile** [comment]
I got a bit triggered by this being deemed a feature and started typing a rant about it, as we just had a server fail due to the cleanup not actually doing anything. (It ran out of space, and yes, we do have monitoring, but the notification channel had been turned off by another team, so we never got to know about it.) Luckily, I calmed down before posting the rant and I took the time to read the documentation to understand how and why this could possibly be deemed a feature.

From the [documentation](https://ruby-doc.org/stdlib-1.9.3/libdoc/fileutils/rdoc/FileUtils.html#method-c-rm_rf):

> This method ignores StandardError when :force option is set.

`rm_rf` is the same as `rm_r` with the force option set. The only difference when not setting the force option is that it will throw an exception and fail, if anything goes wrong. So what OP was asking for was for `rm_rf` to behave like `rm_r`. 

`rm_rf` is useful for cleaning up after a build, where certain directories may or may not have been created (it might have failed before the directory was created), where `rm_r` would fail, because the directory doesn't exist, and cause the rest of the cleanup to not run.

In our case, it wasn't a permissions issue, nor that the directory didn't exist, but the fact that the path had `~` in it. I would be curious to know why `~` doesn't work with `FileUtils`, if anybody knows?

**Comment by deivid-rodriguez** [comment]
Thanks for your feedback.

What I was actually looking for, and what I ended up using is

```ruby
def rm_rf(path)
  FileUtils.remove_entry_secure(path) if File.exist?(path)
end
```

Namely, a `rm_rf` helper that it's only tolerant to giving it files or folders that don't exist, but that it reports any other issue resulting in failing to remove files requested to be removed. Just like shell's `rm -rf` behaves.

Note that there's further development of this issue and it might actually get implemented. See https://github.com/ruby/fileutils/pull/99.

Not sure about `~` by the way!
